### PR TITLE
Create analysis script

### LINKED ISSUE #6: Create analysis script
The processing script should do the following:

T2w
- Segment cord on T2w (0.8mm iso)
- Label vertebrae on T2w
- Register to PAM50 template
- Compute CSA between C2-T5 (average per level)

MTS
- Segment cord on mt-on_MTS
- Register to T2w using spinal cord segmentation
- Register to PAM50 via T2w registration
- Register mt-off to mt-on
- Compute MTR between C2-T5 (average per level) within various tracts/regions

MP2RAGE
- Segment cord on UNI
- Register to T2w using spinal cord segmentation
- Register to PAM50 via T2w registration
- Compute T1 between C2-T5 (average per level) within various tracts/regions

DWI (for each DWI slab):
- Average DWI scans
- Segment spinal cord on mean DWI scan
- Create mask
- Motion correction
- Average DWI scan
- Segment spinal cord on mean DWI_moco scan
- Register to PAM50 via T2w registration
- Compute DTI metrics for all slices within various tracts/regions

DWI merging of slabs:
- Create a script that will combine the three CSV files (one per slab, with some overlap) and that will average the DTI metrics within each vertebral level that exists across the three CSV files.

### PR DESCRIPTION
**Pull request by jcohenadad**
Added analysis script to be run with `sct_run_batch`, and assuming BIDS dataset as input. The script does the processing listed in #6. 

For debugging purpose, this PR can be tested on one subject (faster), as instructed in the README:
https://github.com/sct-pipeline/spine-park/blob/9d780cc67cd15519db437dfc48c4878cdc55030b/README.md?plain=1#L29-L33

At the end of the processing, open the QC report and the output CSV files. 

Fixes https://github.com/sct-pipeline/spine-park/issues/6

### CODE REVIEW

**Comment by Kaonashi22** [comment]
Hi Julien, 

I submitted the script on one subject yesterday; it finished running this morning. The processing of T2 and MT images was relatively fast (about 40 minutes), but it took more than 12 hours for the UNI images. I have attached the log file. Does it have to do with the RAM on my workstation or with the script?

Thanks!
Lydia



[err.batch_processing_sub-DEV159Sujet02.log](https://github.com/sct-pipeline/spine-park/files/14449378/err.batch_processing_sub-DEV159Sujet02.log)
[sct_run_batch_log.txt](https://github.com/sct-pipeline/spine-park/files/14449379/sct_run_batch_log.txt)

**Comment by jcohenadad** [comment]
Version: https://github.com/sct-pipeline/spine-park/pull/8/commits/1b378e0d9ae743b8142716991956e1598dff5dd6

Bug:

~~~
--
Spinal Cord Toolbox (git-jca/4298-flow-d396ad3a9090900cc62d4b6eb4ccbc6d63d4a6eb)

sct_extract_metric -i sub-BB277_T1map.nii.gz -f label_T1/atlas -l 51 -vert 2:12 -vertfile label_T1/template/PAM50_levels.nii.gz -perlevel 1 -method map -o /Users/julien/temp/Lydia/results_20240229_102617/results/T1_in_WM.csv -append 1
--


Load metric image...

ERROR: Metric data and labels DO NOT HAVE SAME DIMENSIONS.
~~~

**Comment by jcohenadad** [comment]
Version: 12624513289de59866abbb6c7735f976d56e3879

<details><summary>Terminal output</summary>

```console
sct_dmri_separate_b0_and_dwi -i sub-BB277_chunk-1_DWI.nii.gz.nii.gz -bvec sub-BB277_chunk-1_DWI.bvec
--


Input parameters:
  input file ............sub-BB277_chunk-1_DWI.nii.gz.nii.gz
  bvecs file ............sub-BB277_chunk-1_DWI.bvec
  bvals file ............
  average ...............1
Creating temporary folder (/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-02-29_11-12-21_dmri-separate-b0-and-dwi_o14mdsvm)

Copy files into temporary folder...
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/julien/temp/Lydia/results_20240229_105533/data_processed/sub-BB277/dwi/sub-BB277_chunk-1_DWI.nii.gz.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_separate_b0_and_dwi.py", line 313, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_separate_b0_and_dwi.py", line 155, in main
    im_dmri = convert(Image(fname_data))
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 285, in __init__
    raise e
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 280, in __init__
    self.loadFromPath(param, mmap, verbose)
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 428, in loadFromPath
    im_file = nib.load(self.absolutepath, mmap=mmap)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/Users/julien/temp/Lydia/results_20240229_105533/data_processed/sub-BB277/dwi/sub-BB277_chunk-1_DWI.nii.gz.nii.gz'
```

</details>

**Comment by jcohenadad** [comment]
Version: 6a445d05a8fc58d7a77fbd2a40dbfaaa45791dc3

~~~
ValueError: File /Users/julien/temp/Lydia/results_20240229_141248/data_processed/sub-BB277/dwi/sub-BB277_chunk-1_DWI.nii.gz has 4 dimensions! Accepted dimensions are: [2, 3].
~~~

<details><summary>Terminal output</summary>

```console

--
Spinal Cord Toolbox (git-jca/4298-flow-d396ad3a9090900cc62d4b6eb4ccbc6d63d4a6eb)

sct_deepseg_sc -i sub-BB277_chunk-1_DWI.nii.gz -c dwi -qc /Users/julien/temp/Lydia/results_20240229_141248/qc -qc-subject sub-BB277
--

Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 211, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 182, in main
    check_dim(fname_image, dim_lst=[2, 3])
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 1453, in check_dim
    raise ValueError(f"File {fname} has {dim[0]} dimensions! Accepted dimensions are: {dim_lst}.")
ValueError: File /Users/julien/temp/Lydia/results_20240229_141248/data_processed/sub-BB277/dwi/sub-BB277_chunk-1_DWI.nii.gz has 4 dimensions! Accepted dimensions are: [2, 3].
```

</details>

**Comment by jcohenadad** [comment]
Version: c2d11fc8e9539934b10293c8665818644055d11f

~~~
FileNotFoundError: No such file or no access: '/Users/julien/temp/Lydia/results_20240229_150654/data_processed/sub-BB277/anat/warp_template2T1w.nii.gz'
~~~

<details><summary>Terminal output</summary>

```console
Spinal Cord Toolbox (git-jca/4298-flow-d396ad3a9090900cc62d4b6eb4ccbc6d63d4a6eb)

sct_register_multimodal -i /Users/julien/code/spinalcordtoolbox/data/PAM50/template/PAM50_t1.nii.gz -iseg /Users/julien/code/spinalcordtoolbox/data/PAM50/template/PAM50_cord.nii.gz -d sub-BB277_chunk-1_DWI_moco_dwi_mean.nii.gz -dseg sub-BB277_chunk-1_DWI_moco_dwi_mean_seg.nii.gz -param step=1,type=seg,algo=centermass:step=2,type=im,algo=syn,metric=CC,iter=5,gradStep=0.5 -initwarp ../anat/warp_template2T1w.nii.gz -initwarpinv ../anat/warp_T1w2template.nii.gz -qc /Users/julien/temp/Lydia/results_20240229_150654/qc
--


Input parameters:
  Source .............. /Users/julien/code/spinalcordtoolbox/data/PAM50/template/PAM50_t1.nii.gz (141, 141, 991)
  Destination ......... sub-BB277_chunk-1_DWI_moco_dwi_mean.nii.gz (184, 138, 15)
  Init transfo ........ /Users/julien/temp/Lydia/results_20240229_150654/data_processed/sub-BB277/anat/warp_template2T1w.nii.gz
  Mask ................ 
  Output name ......... 
  Remove temp files ... 1
  Verbose ............. 1

Check if input data are 3D...
Creating temporary folder (/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-02-29_15-28-05_register-wrapper_zlnykwfo)

Copying input data to tmp folder and convert to nii...

Skip step=0 and replace with initial transformations: 
  /Users/julien/temp/Lydia/results_20240229_150654/data_processed/sub-BB277/anat/warp_template2T1w.nii.gz

--
ESTIMATE TRANSFORMATION FOR STEP #1

Apply transformation from previous step
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/julien/temp/Lydia/results_20240229_150654/data_processed/sub-BB277/anat/warp_template2T1w.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 444, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 416, in main
    register_wrapper(fname_src, fname_dest, param, paramregmulti, fname_src_seg=fname_src_seg,
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/registration/core.py", line 171, in register_wrapper
    sct_apply_transfo.main(argv=[
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_apply_transfo.py", line 353, in main
    transform.apply()
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_apply_transfo.py", line 160, in apply
    and Image(list_warp[idx_warp]).header.get_intent()[0] != 'vector':
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 285, in __init__
    raise e
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 280, in __init__
    self.loadFromPath(param, mmap, verbose)
  File "/Users/julien/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 428, in loadFromPath
    im_file = nib.load(self.absolutepath, mmap=mmap)
  File "/Users/julien/code/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/Users/julien/temp/Lydia/results_20240229_150654/data_processed/sub-BB277/anat/warp_template2T1w.nii.gz'
```

</details>

**Pull request merged**
